[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pricing-optimizer"
version = "0.1.0"
description = "Pricing optimization project"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["packages"] 