version: "3.8"

services:
  ai-server:
    build:
      context: ../.. # Points to the monorepo root
      dockerfile: infra/compose/ai-server.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ../../apps/ai-server:/app # For development hot-reloading
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
