name: AI Server CI/CD

on:
  push:
    branches: [main, dev]
    paths:
      - "apps/frontend/**"
      - "apps/ai-server/**"
      - "packages/**"
      - ".github/workflows/**"
  pull_request:
    branches: [main, dev]
    paths:
      - "apps/frontend/**"
      - "apps/ai-server/**"
      - "packages/**"
      - ".github/workflows/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "apps/ai-server/requirements.txt"

      - name: Install dependencies
        run: |
          cd apps/ai-server
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov black isort mypy

      - name: Format code
        run: |
          cd apps/ai-server
          black .
          isort .

      - name: Run tests
        run: |
          cd apps/ai-server
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./apps/ai-server/coverage.xml
          fail_ci_if_error: true
